/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type FormStatus = "errored" | "ready" | "received";

export type GenderTransformed = "female" | "male" | "prefer-not-to-say";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface IngestedForms {
  applicationRef: string;
  errorMessage: string | null;
  id: Generated<string>;
  latitude: Numeric | null;
  longitude: Numeric | null;
  rawPayload: Json;
  receivedAt: Generated<Timestamp>;
  sessionId: string | null;
  status: Generated<FormStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface TransformedForms {
  addressLine1: string;
  addressLine2: string;
  addressLine3: string | null;
  applicationReference: string;
  country: string;
  createdAt: Generated<Timestamp>;
  dateOfBirth: Timestamp;
  email: string;
  emailSentAt: Timestamp | null;
  firstName: string;
  gender: GenderTransformed;
  id: Generated<string>;
  ingestedFormId: string;
  lastName: string;
  latitude: Numeric;
  longitude: Numeric;
  mobileNumber: string;
  phoneNumber: string | null;
  postcode: string;
  sessionId: string;
}

export interface DB {
  ingestedForms: IngestedForms;
  transformedForms: TransformedForms;
}
